### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind": bind source path doesn't exist 

### ISSUE THREAD

**Issue by samboluy** [ritual-net/infernet-container-starter#2]
hi Team, when trying to do docker compose up -d i hit the error below:

root@racknerd-4342f0:~/infernet-container-starter# project=hello-world make deploy-container
cp ./projects/hello-world/container/config.json deploy/config.json
cd deploy && docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.node.volumes contains an invalid type, it should be a string
Makefile:2: recipe for target 'deploy-container' failed
make: *** [deploy-container] Error 1
root@racknerd-4342f0:~/infernet-container-starter# cd deploy
root@racknerd-4342f0:~/infernet-container-starter/deploy# docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.node.volumes contains an invalid type, it should be a string
root@racknerd-4342f0:~/infernet-container-starter/deploy# ERROR: The Compose file './docker-compose.yaml' is invalid because:
-bash: ERROR:: command not found
root@racknerd-4342f0:~/infernet-container-starter/deploy# services.node.volumes contains an invalid type, it should be a string
-bash: services.node.volumes: command not found
root@racknerd-4342f0:~/infernet-container-starter/deploy#

**Comment by samboluy** [comment]
> hi Team, when trying to do docker compose up -d i hit the error below:
> 
> [+] Running 5/5 ✔ Network deploy_network Created 0.1s ✔ Volume "deploy_redis-data" Created 0.0s ✔ Volume "deploy_node-logs" Created 0.0s ✔ Container deploy-fluentbit-1 Created 0.9s ✔ Container deploy-redis-1 Created 0.9s ⠋ Container deploy-node-1 Creating 0.0s Error response from daemon: invalid mount config for type "bind": bind source pa th does not exist: /root/infernet-container-starter/deploy/config.json

I found my own solution now, I need to go to deploy folder and do this: cp ../projects/hello-world/container/config.json config.json

But then my question is: what is the wallet I should put and what private key I should put? the EVM address from my metamask?

**Comment by samboluy** [comment]
I hit error: when make register node:

root@racknerd-4342f0:~/infernet-container-starter/deploy# docker exec 63d9c789680f make register-node
OCI runtime exec failed: exec failed: unable to start container process: exec: "make": executable file not found in $PATH: unknown
root@racknerd-4342f0:~/infernet-container-starter/deploy#

**Comment by stelios-ritual** [comment]
Thanks for flagging, will include fix in next release.

In the meantime, replacing
```
type: bind
source: ./config.json
target: /app/config.json
```

with 
```
./config.json:/app/config.json
```

in `docker-compose.yaml` should fix the issue.
