### ISSUE TITLE
Avoid Using "latest" Tag in docker-compose.yml for Redis and Fluentbit

### ISSUE THREAD

**Issue by kbakdev** [ritual-net/infernet-container-starter#22]
The current `docker-compose.yml` configuration specifies the use of the latest tag for both Redis and Fluentbit images. Using the latest tag is not recommended because it can lead to potential compatibility issues when the image updates. The latest tag does not guarantee backward compatibility, which can cause unexpected failures or behavior changes when the images are updated.

Affected places:

- https://github.com/ritual-net/infernet-container-starter/blob/ba94d1563d14469057f842c85ea8e9dee273d24d/deploy/docker-compose.yaml#L26
- https://github.com/ritual-net/infernet-container-starter/blob/ba94d1563d14469057f842c85ea8e9dee273d24d/deploy/docker-compose.yaml#L38

**Comment by stelios-ritual** [comment]
thanks for the suggestion, will do!
